### ISSUE TITLE
Possible to find current calendar appointment?

### ISSUE THREAD

**Issue by tommybobbins** [wreckage/django-happenings#7]
Hello Wreckage,

This is a great project and I'm really interested in using it for my Internet of Things home automation scheduler. I've got it working brilliantly so that I can see the upcoming appointments using , however, I'd really like to know what the current happening is:

sqlite> select * from happenings_event;
1|2015-05-20 23:01:01|2015-05-21 05:00:00|0|WEEKDAY||Temp=7.2|Temp=7|000000||eeeeee||1
2|2015-05-21 05:00:00|2015-05-21 09:00:00|0|WEEKDAY||Temp=19|Temp=19.1|0000ff||ffffff||1
3|2015-05-21 09:00:00|2015-05-21 16:00:00|0|WEEKDAY||Temp=8|Temp=8.1|ff0000||ffffff||1
4|2015-05-21 16:00:00|2015-05-21 21:00:00|0|WEEKDAY||Temp=19|Temp=19|eeeeee||000000||1
5|2015-05-21 21:00:00|2015-05-21 22:59:59|0|WEEKDAY||Temp=7.3|Temp=7.3|00ff00||ffffff||1

{% load happenings_tags %}
{% upcoming_events num=1 finish=0 %}

Doesn't appear to display the current happening: It always displays:
May 22 Fri Temp=7.2

**Comment by wreckage** [comment]
Hello, and thank you for your interest. I think I understand the problem: If events are scheduled to happen, say, today, you want to display the very next event that is going to happen today. Correct? I think the issue is that the time of an event isn't being checked against the current time, so events that started earlier in the day (and so really are no longer "upcoming") are still showing up. Am I understanding correctly? If this is the problem, I think I've nearly got it fixed and I'm just cleaning up some things in the code.
Or do you want the events that are currently going on? Like the events that are happening right now, sorted by earliest starting time?

**Comment by tommybobbins** [comment]
Thanks very much for the update wreckage.
 Ideally, I'd like the second thing - a currently happening event - as in an event that has passed it's start time, but not it's end time. 
I think your code is and will be incredibly useful for many projects.

**Comment by tommybobbins** [comment]
Didn't mean to close and comment.

**Comment by wreckage** [comment]
I think it's a good idea; I'll try adding this as a separate template tag, instead of lumping it with the upcoming_events tag. I'm currently working on making upcoming_events (and the get_next_event() function) aware of the time of day, so that events finished for the day don't get displayed. The way it is now, the app just goes by the day of the event, so an event might have finished earlier in the day, but it'll still be displayed as an 'upcoming event' for that same day. I believe this will also make it easier to implement the new tag.

**Comment by wreckage** [comment]
Sorry for the long delay, but I've just finished work on the new current_happenings tag. Include it with 
{% current_happenings %}
It'll display a list of events happening now (just realized it displays 'Oops... no events!' when there's no events, I'll change it to something better with the next release, but of course the best thing to do is to create your own happening_events.html template to overwrite the default one). I believe it works as it should, let me know if you find anything wrong with it. For more details view the CHANGELOG.

Also, the current_happenings and upcoming_events tags work separately, and as of right now using both results in separate database queries for the two tags. I'll work on fixing this to somehow combine the two and save on db queries.

**Comment by tommybobbins** [comment]
Thanks wreckage. New code working perfectly.
